cache:
  directories:
    - target/debug/fingerprint
    - target/debug/deps

language: rust

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

rust:
  - 1.0.0
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --no-deps
