cache:
  directories:
    - target/debug/fingerprint
    - target/debug/deps

language: rust

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

os:
  - linux
  - osx

rust:
  - 1.0.0
  - stable
  - beta
  - nightly

script:
  - "cargo build --verbose"
  - "cargo test --verbose"
  - "cargo doc --no-deps"

  sudo: false
