language: rust

notifications:
  email:
    on_success: never

rust:
  - 1.0.0
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --no-deps
